services:
  # Zookeeper for Kafka Coordination
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: ${ZOOKEEPER_ANONYMOUS_LOGIN}
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  # Kafka for Real-Time Data Streaming
  kafka:
    image: bitnami/kafka:2.8.1
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      ALLOW_PLAINTEXT_LISTENER: ${KAFKA_ALLOW_PLAINTEXT_LISTENER}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    networks:
      - kafka_network

  # Kafka Manager for Web UI
  kafka-manager:
    image: hlebalbau/kafka-manager:stable
    environment:
      ZK_HOSTS: ${KAFKA_ZOOKEEPER_CONNECT}
      APPLICATION_SECRET: ${KAFKA_APPLICATION_SECRET}
    ports:
      - "9000:9000"
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka_network

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka_network

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_RETENTION}
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_network

  # Kafka Topic Creation Service
  kafka-create-topics:
    image: bitnami/kafka:latest
    depends_on:
      - kafka
    volumes:
      - ./configs/create_kafka_topics.sh:/create_kafka_topics.sh
    entrypoint: ["bash", "/create_kafka_topics.sh"]
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
