services:
  # Zookeeper for Kafka Coordination
  zookeeper:
    image: bitnami/zookeeper:latest
    environment:
      ALLOW_ANONYMOUS_LOGIN: 1
    ports:
      - "2181:2181"
    networks:
      - kafka_network

  # Kafka for Real-Time Data Streaming
  kafka:
    image: bitnami/kafka:2.8.1
    environment:
      KAFKA_BROKER_ID: ${KAFKA_BROKER_ID}
      KAFKA_ZOOKEEPER_CONNECT: ${KAFKA_ZOOKEEPER_CONNECT}
      ALLOW_PLAINTEXT_LISTENER: ${KAFKA_ALLOW_PLAINTEXT_LISTENER}
      KAFKA_LISTENERS: ${KAFKA_LISTENERS}
      KAFKA_ADVERTISED_LISTENERS: ${KAFKA_ADVERTISED_LISTENERS}
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: ${KAFKA_LISTENER_SECURITY_PROTOCOL_MAP}
      KAFKA_INTER_BROKER_LISTENER_NAME: ${KAFKA_INTER_BROKER_LISTENER_NAME}
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: ${KAFKA_AUTO_CREATE_TOPICS_ENABLE}
    ports:
      - "9092:9092"  # Expose external listener
    depends_on:
      - zookeeper
    networks:
      - kafka_network
    restart: always
    healthcheck:
      test: ["CMD", "/opt/bitnami/kafka/bin/kafka-topics.sh", "--bootstrap-server", "localhost:9092", "--list"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Producer Service
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: spark-scripts/kafka_producer_swat.py
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./spark-scripts:/app/spark-scripts  
      - ./dataset/filtered:/app/dataset            
    networks:
      - kafka_network
    restart: always
    healthcheck:
      test: ["CMD", "python", "/app/spark-scripts/kafka_producer_swat.py", "--check"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Consumer Service
  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: spark-scripts/kafka_consumer_swat.py
    env_file:
      - .env
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
      - ./spark-scripts:/app/spark-scripts  
    networks:
      - kafka_network
    restart: always
    healthcheck:
      test: ["CMD", "python", "/app/spark-scripts/kafka_consumer_swat.py", "--check"]
      interval: 10s
      timeout: 5s
      retries: 3

  # Grafana for Visualization
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - zookeeper
      - kafka
    networks:
      - kafka_network

  influxdb:
    image: influxdb:2.0
    ports:
      - "8086:8086"
    environment:
      DOCKER_INFLUXDB_INIT_MODE: ${INFLUXDB_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${INFLUXDB_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${INFLUXDB_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${INFLUXDB_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${INFLUXDB_BUCKET1}
      DOCKER_INFLUXDB_INIT_RETENTION: ${INFLUXDB_RETENTION}
    depends_on:
      - kafka
      - zookeeper
    networks:
      - kafka_network

  # Kafka Topic Creation Service
  kafka-create-topics:
    image: bitnami/kafka:2.8.1
    depends_on:
      - kafka
    volumes:
      - ./configs/create_kafka_topics.sh:/create_kafka_topics.sh
    entrypoint: ["bash", "/create_kafka_topics.sh"]
    networks:
      - kafka_network

networks:
  kafka_network:
    driver: bridge
